// Code generated by tools/build_schema_tables.py from contract/analytic.toml. DO NOT EDIT.

package analytic

// Digest is compared to irgx_schema_digest() at load — a stale library is a
// loud failure, not a mis-decoded row.
const Digest = "fe410e7f8ccb9a62c71bd28161f2e080"

const maxFields = 64

// FieldDef is one declared field of one row schema.
type FieldDef struct {
	Name     string
	Tag      uint32
	Nested   uint32
	Optional bool
}

// SchemaDef is one declared row schema; Fields order is value order.
type SchemaDef struct {
	ID     uint32
	Name   string
	Fields []FieldDef
}

// VerbDef binds a verb to its op code, params family, row schema, and the C
// symbol that answers it — one run entry per face library. Ops are
// ecosystem-wide, so Entry is the only thing that says which library to ask.
type VerbDef struct {
	Op     uint32
	Name   string
	Params string
	Schema uint32
	Many   bool
	Entry  string
}

// enums maps an enum name to its variants; an ordinal past the end is unknown.
var enums = map[string][]string{
	"grade":     {"none", "weak", "moderate", "strong", "identical"},
	"channel":   {"copies", "twins", "shapes", "any"},
	"unit":      {"file", "function", "match"},
	"rank_kind": {"definition", "use", "generated"},
}

// enumByID resolves a field's Nested back to its enum name.
var enumByID = map[uint32]string{
	1: "grade",
	2: "channel",
	3: "unit",
	4: "rank_kind",
}

// schemas is indexed by ID-1.
var schemas = []SchemaDef{
	{1, "region", []FieldDef{{"path", 0, 0, false}, {"line_start", 1, 0, false}, {"line_end", 1, 0, false}, {"headline", 0, 0, true}}},
	{2, "site", []FieldDef{{"path", 0, 0, false}, {"line", 1, 0, false}}},
	{3, "similar", []FieldDef{{"path", 0, 0, false}, {"distance", 2, 0, false}, {"grade", 4, 1, false}, {"channel", 4, 2, false}}},
	{4, "dup_pair", []FieldDef{{"a", 0, 0, false}, {"b", 0, 0, false}, {"distance", 2, 0, false}, {"grade", 4, 1, false}}},
	{5, "cluster", []FieldDef{{"paths", 5, 0, false}, {"max_distance", 2, 0, false}, {"grade", 4, 1, false}}},
	{6, "echo", []FieldDef{{"a", 0, 0, false}, {"b", 0, 0, false}, {"echo", 2, 0, false}, {"byte_distance", 2, 0, false}, {"structure_distance", 2, 0, false}, {"grade", 4, 1, false}}},
	{7, "concept", []FieldDef{{"members", 6, 1, false}, {"repeated_lines", 1, 0, false}, {"confidence", 2, 0, false}, {"structure_distance", 2, 0, false}, {"byte_distance", 2, 0, true}, {"echo", 2, 0, true}}},
	{8, "family", []FieldDef{{"rank", 1, 0, false}, {"unit", 4, 3, false}, {"channel", 4, 2, false}, {"edge", 2, 0, false}, {"repeated_lines", 1, 0, false}, {"score", 2, 0, false}, {"members", 6, 1, false}}},
	{9, "distinct", []FieldDef{{"unit", 4, 3, false}, {"member", 6, 1, false}, {"nearest", 6, 1, true}, {"byte_distance", 2, 0, false}, {"structure_distance", 2, 0, false}}},
	{10, "recalled", []FieldDef{{"path", 0, 0, false}, {"gain", 2, 0, false}, {"cost_bits", 2, 0, false}, {"bits_saved", 2, 0, false}, {"factors", 1, 0, false}, {"literals", 1, 0, false}}},
	{11, "pick", []FieldDef{{"rank", 1, 0, false}, {"path", 0, 0, false}, {"marginal_bits", 2, 0, false}, {"coverage", 2, 0, false}, {"patterns", 5, 0, false}}},
	{12, "phrase", []FieldDef{{"text", 0, 0, false}, {"occurrences", 1, 0, false}, {"bits", 2, 0, false}, {"source", 0, 0, true}}},
	{13, "quotation", []FieldDef{{"bits", 2, 0, false}, {"bits_per_byte", 2, 0, false}, {"quoted_bytes", 1, 0, false}, {"query_bytes", 1, 0, false}, {"escapes", 1, 0, false}, {"phrases", 6, 12, false}}},
	{14, "attribution", []FieldDef{{"text", 0, 0, false}, {"occurrences", 1, 0, false}, {"source", 0, 0, true}, {"verified", 3, 0, false}, {"line", 1, 0, true}}},
	{15, "pattern_hit", []FieldDef{{"path", 0, 0, false}, {"line", 1, 0, false}, {"pattern_id", 1, 0, false}}},
	{16, "pattern_count", []FieldDef{{"label", 0, 0, false}, {"count", 1, 0, false}}},
	{17, "reference", []FieldDef{{"path", 0, 0, false}, {"line", 1, 0, false}, {"enclosing", 0, 0, true}, {"defines", 3, 0, false}}},
	{18, "dependency", []FieldDef{{"symbol", 0, 0, false}, {"path", 0, 0, false}, {"line", 1, 0, false}}},
	{19, "ripple", []FieldDef{{"path", 0, 0, false}, {"via", 0, 0, false}, {"hops", 1, 0, false}}},
	{20, "mention", []FieldDef{{"path", 0, 0, false}, {"line", 1, 0, false}, {"text", 0, 0, false}}},
	{21, "blast", []FieldDef{{"symbol", 0, 0, false}, {"kind", 0, 0, false}, {"definitions", 6, 2, false}, {"dependents", 6, 17, false}, {"dependencies", 6, 18, false}, {"twins", 6, 3, false}, {"ripple", 6, 19, false}, {"comments", 6, 20, false}, {"notes", 5, 0, false}, {"omitted", 1, 0, false}}},
	{22, "ranked", []FieldDef{{"path", 0, 0, false}, {"line_number", 1, 0, false}, {"kind", 4, 4, false}, {"count", 1, 0, false}, {"snippet", 0, 0, true}}},
}

// verbs is indexed by Op-1.
var verbs = []VerbDef{
	{1, "similar", "kinship", 3, true, "relate_run"},
	{2, "dups", "kinship", 4, true, "relate_run"},
	{3, "clusters", "kinship", 5, true, "relate_run"},
	{4, "echoes", "kinship", 6, true, "relate_run"},
	{5, "concepts", "kinship", 7, true, "relate_run"},
	{6, "fragments", "kinship", 8, true, "relate_run"},
	{7, "distinct", "kinship", 9, true, "relate_run"},
	{8, "recall", "retrieval", 10, true, "relate_run"},
	{9, "pack", "retrieval", 11, true, "relate_run"},
	{10, "quote", "retrieval", 13, false, "relate_run"},
	{11, "patterns", "sweep", 15, true, "relate_run"},
	{12, "pattern_counts", "sweep", 16, true, "relate_run"},
	{13, "context", "compose", 11, true, "blast_run"},
	{14, "family", "compose", 8, true, "blast_run"},
	{15, "provenance", "compose", 14, true, "blast_run"},
	{16, "blast", "compose", 21, false, "blast_run"},
	{17, "rank", "rank", 22, true, "gist_run"},
}
