"""Generated by tools/build_schema_tables.py from contract/analytic.toml — DO NOT EDIT.

The analytic plane's row-schema table. `runtime/decode.py` walks
it to turn an `irgx_row` into a typed record; nothing here is
hand-written, so a new verb cannot drift from the engine.
"""

from __future__ import annotations

from typing import Final

DIGEST: Final = "fe410e7f8ccb9a62c71bd28161f2e080"
TAGS: Final = ('text', 'i64', 'f64', 'bool', 'enum', 'texts', 'rows')
MAX_FIELDS: Final = 64

# name -> ordinal -> variant. An ordinal past the end is UNKNOWN, never guessed.
ENUMS: Final[dict[str, tuple[str, ...]]] = {
    'grade': ('none', 'weak', 'moderate', 'strong', 'identical'),
    'channel': ('copies', 'twins', 'shapes', 'any'),
    'unit': ('file', 'function', 'match'),
    'rank_kind': ('definition', 'use', 'generated'),
}

# id -> (name, ((field, tag, nested, optional), ...)). Field order is value order.
SCHEMAS: Final[dict[int, tuple[str, tuple[tuple[str, int, int, bool], ...]]]] = {
    1: ('region', (('path', 0, 0, False), ('line_start', 1, 0, False), ('line_end', 1, 0, False), ('headline', 0, 0, True),)),
    2: ('site', (('path', 0, 0, False), ('line', 1, 0, False),)),
    3: ('similar', (('path', 0, 0, False), ('distance', 2, 0, False), ('grade', 4, 1, False), ('channel', 4, 2, False),)),
    4: ('dup_pair', (('a', 0, 0, False), ('b', 0, 0, False), ('distance', 2, 0, False), ('grade', 4, 1, False),)),
    5: ('cluster', (('paths', 5, 0, False), ('max_distance', 2, 0, False), ('grade', 4, 1, False),)),
    6: ('echo', (('a', 0, 0, False), ('b', 0, 0, False), ('echo', 2, 0, False), ('byte_distance', 2, 0, False), ('structure_distance', 2, 0, False), ('grade', 4, 1, False),)),
    7: ('concept', (('members', 6, 1, False), ('repeated_lines', 1, 0, False), ('confidence', 2, 0, False), ('structure_distance', 2, 0, False), ('byte_distance', 2, 0, True), ('echo', 2, 0, True),)),
    8: ('family', (('rank', 1, 0, False), ('unit', 4, 3, False), ('channel', 4, 2, False), ('edge', 2, 0, False), ('repeated_lines', 1, 0, False), ('score', 2, 0, False), ('members', 6, 1, False),)),
    9: ('distinct', (('unit', 4, 3, False), ('member', 6, 1, False), ('nearest', 6, 1, True), ('byte_distance', 2, 0, False), ('structure_distance', 2, 0, False),)),
    10: ('recalled', (('path', 0, 0, False), ('gain', 2, 0, False), ('cost_bits', 2, 0, False), ('bits_saved', 2, 0, False), ('factors', 1, 0, False), ('literals', 1, 0, False),)),
    11: ('pick', (('rank', 1, 0, False), ('path', 0, 0, False), ('marginal_bits', 2, 0, False), ('coverage', 2, 0, False), ('patterns', 5, 0, False),)),
    12: ('phrase', (('text', 0, 0, False), ('occurrences', 1, 0, False), ('bits', 2, 0, False), ('source', 0, 0, True),)),
    13: ('quotation', (('bits', 2, 0, False), ('bits_per_byte', 2, 0, False), ('quoted_bytes', 1, 0, False), ('query_bytes', 1, 0, False), ('escapes', 1, 0, False), ('phrases', 6, 12, False),)),
    14: ('attribution', (('text', 0, 0, False), ('occurrences', 1, 0, False), ('source', 0, 0, True), ('verified', 3, 0, False), ('line', 1, 0, True),)),
    15: ('pattern_hit', (('path', 0, 0, False), ('line', 1, 0, False), ('pattern_id', 1, 0, False),)),
    16: ('pattern_count', (('label', 0, 0, False), ('count', 1, 0, False),)),
    17: ('reference', (('path', 0, 0, False), ('line', 1, 0, False), ('enclosing', 0, 0, True), ('defines', 3, 0, False),)),
    18: ('dependency', (('symbol', 0, 0, False), ('path', 0, 0, False), ('line', 1, 0, False),)),
    19: ('ripple', (('path', 0, 0, False), ('via', 0, 0, False), ('hops', 1, 0, False),)),
    20: ('mention', (('path', 0, 0, False), ('line', 1, 0, False), ('text', 0, 0, False),)),
    21: ('blast', (('symbol', 0, 0, False), ('kind', 0, 0, False), ('definitions', 6, 2, False), ('dependents', 6, 17, False), ('dependencies', 6, 18, False), ('twins', 6, 3, False), ('ripple', 6, 19, False), ('comments', 6, 20, False), ('notes', 5, 0, False), ('omitted', 1, 0, False),)),
    22: ('ranked', (('path', 0, 0, False), ('line_number', 1, 0, False), ('kind', 4, 4, False), ('count', 1, 0, False), ('snippet', 0, 0, True),)),
}

ENUM_BY_ID: Final[dict[int, str]] = {1: 'grade', 2: 'channel', 3: 'unit', 4: 'rank_kind'}

# verb -> (op, params family, schema id, streams many rows, entry symbol)
VERBS: Final[dict[str, tuple[int, str, int, bool, str]]] = {
    'similar': (1, 'kinship', 3, True, 'relate_run'),
    'dups': (2, 'kinship', 4, True, 'relate_run'),
    'clusters': (3, 'kinship', 5, True, 'relate_run'),
    'echoes': (4, 'kinship', 6, True, 'relate_run'),
    'concepts': (5, 'kinship', 7, True, 'relate_run'),
    'fragments': (6, 'kinship', 8, True, 'relate_run'),
    'distinct': (7, 'kinship', 9, True, 'relate_run'),
    'recall': (8, 'retrieval', 10, True, 'relate_run'),
    'pack': (9, 'retrieval', 11, True, 'relate_run'),
    'quote': (10, 'retrieval', 13, False, 'relate_run'),
    'patterns': (11, 'sweep', 15, True, 'relate_run'),
    'pattern_counts': (12, 'sweep', 16, True, 'relate_run'),
    'context': (13, 'compose', 11, True, 'blast_run'),
    'family': (14, 'compose', 8, True, 'blast_run'),
    'provenance': (15, 'compose', 14, True, 'blast_run'),
    'blast': (16, 'compose', 21, False, 'blast_run'),
    'rank': (17, 'rank', 22, True, 'gist_run'),
}
