/* Does the published header parse as plain C99, with nothing to forgive?
 *
 * The header is generated by nobody: it is written by hand beside the Zig shims
 * it describes, and the compiler that reads it most often here is Zig's own,
 * through cgo, at whatever default the toolchain picked. So the standard the
 * header claims to speak was never actually asked of it. A `//` comment, a
 * trailing comma in an enum, an anonymous union, a `bool` without stdbool — each
 * is fine under that default and each is a host's build breaking on a header we
 * published.
 *
 * `-pedantic-errors` is the whole point. Warnings are what nobody reads.
 *
 * Compiled, never linked: `zig build header` produces an object and throws it
 * away. The probe therefore has to USE the types rather than merely name them,
 * because an incomplete struct is only a fault at the point somebody needs its
 * size, which is the point a host reaches. */

#include <stddef.h>

#include "irgx.h"

int irgx_header_probe_c99(void);

int irgx_header_probe_c99(void)
{
    /* One from each family: the fault channel, the two borrowed vocabularies,
     * a match, the request and options a search is asked for, the analytic row
     * schema, and a line of context. A struct that stopped being a complete
     * type fails here rather than in whoever linked us. */
    size_t sizes = sizeof(irgx_fault) + sizeof(irgx_text) + sizeof(irgx_span) +
                   sizeof(irgx_match) + sizeof(irgx_input) + sizeof(irgx_options) +
                   sizeof(irgx_schema) + sizeof(irgx_line) + sizeof(irgx_stats);
    const char *release = irgx_version();
    return (int)sizes + (int)irgx_abi_version() + (release != NULL);
}
