//! Tests for the ranking signals. The risk is twofold: a def-keyword set that
//! only fires on a few languages (silently flattening the def-boost on the rest)
//! and a generated detector that misses a marker an agent then can't demote. So
//! these assert definition detection across the mainstream ecosystem, the
//! use-vs-decl discriminators (a `=`/quote/comma before the needle is a use),
//! and generated detection by both suffix and universal header marker.

const std = @import("std");
const signals = @import("signals.zig");
const expect = std.testing.expect;

test "definesNeedle fires across the language ecosystem" {
    try expect(signals.definesNeedle("func NewWallet(cc grpc.ClientConn) Wallet {", "NewWallet"));
    try expect(signals.definesNeedle("pub fn parse(self: *T) !void {", "parse"));
    try expect(signals.definesNeedle("def charge(self, amount):", "charge"));
    try expect(signals.definesNeedle("class WalletService:", "WalletService"));
    try expect(signals.definesNeedle("fun computeBalance(): Long {", "computeBalance")); // Kotlin
    try expect(signals.definesNeedle("function getWallet() {", "getWallet")); // JS/TS
    try expect(signals.definesNeedle("type Wallet struct {", "Wallet")); // Go type
    try expect(signals.definesNeedle("interface WalletService {", "WalletService"));
    try expect(signals.definesNeedle("trait Charge {", "Charge")); // Rust
    try expect(signals.definesNeedle("defmodule Wallet do", "Wallet")); // Elixir
    try expect(signals.definesNeedle("sub charge {", "charge")); // Perl
    try expect(signals.definesNeedle("    const MaxRetries = 5", "MaxRetries"));
    // Go method with a receiver — the `(` before the name must stay legal.
    try expect(signals.definesNeedle("func (s *Service) Charge(amount int64) error {", "Charge"));
}

test "definesNeedle rejects uses, strings, RHS, and mid-identifier hits" {
    try expect(!signals.definesNeedle("    w := NewWallet(cc)", "NewWallet")); // call site
    try expect(!signals.definesNeedle("    return charge(amount)", "charge")); // call site
    try expect(!signals.definesNeedle("    var x = WalletService", "WalletService")); // RHS of =
    try expect(!signals.definesNeedle("    log(\"WalletService started\")", "WalletService")); // string
    try expect(!signals.definesNeedle("    fields := []T{Wallet, Ledger}", "Wallet")); // list element (comma)
    try expect(!signals.definesNeedle("type WalletServiceImpl struct {", "WalletService")); // mid-identifier
    try expect(!signals.definesNeedle("plain text with charge in it", "charge")); // no def kw
}

test "isGenerated by ecosystem suffix" {
    const empty = "";
    try expect(signals.isGenerated("services/api/wallet.pb.go", empty)); // Go protobuf
    try expect(signals.isGenerated("x/wallet_pb2.py", empty)); // Python protobuf
    try expect(signals.isGenerated("x/wallet_pb2_grpc.py", empty)); // Python grpc
    try expect(signals.isGenerated("x/Wallet.pb.cc", empty)); // C++ protobuf
    try expect(signals.isGenerated("x/wallet.g.dart", empty)); // Dart codegen
    try expect(signals.isGenerated("x/Wallet.designer.cs", empty)); // C# designer
    try expect(signals.isGenerated("x/app.min.js", empty)); // minified
    try expect(!signals.isGenerated("services/api/wallet.go", empty)); // hand-written
    try expect(!signals.isGenerated("services/api/handler.py", empty));
}

test "isGenerated by universal first-line marker (language-independent)" {
    try expect(signals.isGenerated("a.go", "// Code generated by protoc. DO NOT EDIT.\npackage x\n"));
    try expect(signals.isGenerated("a.py", "# Generated by the protocol buffer compiler.\nimport x\n"));
    try expect(signals.isGenerated("a.ts", "/* @generated */\nexport {}\n"));
    try expect(signals.isGenerated("a.rs", "// AUTO-GENERATED FILE, DO NOT EDIT\n"));
    try expect(signals.isGenerated("a.sql", "-- Autogenerated migration\n"));
    // a body mention must NOT trip it — markers are first-line only.
    try expect(!signals.isGenerated("a.go", "package x\n// this discusses Code generated files\n"));
    try expect(!signals.isGenerated("a.go", "package main\nfunc main() {}\n"));
}
