#!/usr/bin/env python3
"""gist lowerbound — Layer D certificate splicer (algorithmic / information-theoretic floor).

The Zig audit (`bench/bounds/lowerbound/audit.zig`) writes `lowerbound.csv`: for
each regex class it records the candidate byte set the trigram filter admits and
the bytes an INDEPENDENT single-pass reference touches to verify them. This
reads that CSV and rewrites the `## Layer D — algorithmic lower bound` section of
CERTIFICATE.md in place — the formal argument (with the classical citations)
followed by the empirical table proving gist sits at the floor.

The floor, in one breath:
  • VERIFY. Confirming whether a pattern occurs in a candidate document forces
    Ω(n) byte reads in the worst case — you cannot certify a byte's absence
    without examining it (the adversary flips an unread byte). Knuth-Morris-Pratt
    (1977) and Boyer-Moore (1977) are the classical linear-time exact-match
    results; Boyer-Moore is sublinear on *average* but still Ω(n/m) reads
    minimum, and the *verify-stage* floor is Ω(candidate bytes). gist's fused
    byte-class DFA reads each candidate byte EXACTLY once
    (`src/kernel/regex/linear/dfa/dfa.zig`);
    its SIMD literal path reads ≤ N (vector skips + early exit).
  • PRUNE. Total work is sublinear in corpus size because the trigram index
    admits only a fraction of documents before verify ever runs (Cox, 2012 — the
    Google Code Search trigram index gist descends from). `cand%` is that
    fraction, measured.

stdlib only. Mirrors `gist/bench/certificate/report/stats.py`'s splice technique.
"""

# This file emits the certificate's Layer-D markdown, which intentionally carries
# math/typography glyphs (Omega, leq, middot, en/em dashes) that ruff's
# ambiguous-unicode rules flag; the glyphs are the certificate's contract, so
# silence them file-wide (same posture as other long-running report scripts
# ignore RUF001/002/003 for intentional glyphs).

import argparse
import csv
import os
from dataclasses import dataclass
from pathlib import Path

LAYER_D_HEADER = "## Layer D — algorithmic lower bound (information-theoretic floor)"


@dataclass
class Row:
    """One lower-bound benchmark measurement row."""

    cls: str
    kind: str
    cand_docs: int
    corpus_docs: int
    cand_bytes: int
    corpus_bytes: int
    cand_byte_frac: float
    examined: int
    passes: float
    hits: int
    engine: str
    at_floor: bool


def load_rows(csv_path: Path) -> list[Row]:
    """Load rows from disk."""
    with csv_path.open() as fh:
        return [
            Row(
                cls=r["class"],
                kind=r["kind"],
                cand_docs=int(r["cand_docs"]),
                corpus_docs=int(r["corpus_docs"]),
                cand_bytes=int(r["candidate_bytes"]),
                corpus_bytes=int(r["corpus_bytes"]),
                cand_byte_frac=float(r["cand_byte_frac"]),
                examined=int(r["examined_bytes"]),
                passes=float(r["passes"]),
                hits=int(r["hits"]),
                engine=r["engine"],
                at_floor=r["at_floor"].strip() in ("1", "true", "True"),
            )
            for r in csv.DictReader(fh, delimiter="\t")
        ]


def _mib(n: int) -> str:
    return f"{n / (1 << 20):.1f} MiB"


def render(rows: list[Row]) -> str:
    """Render generated source artifacts."""
    lines: list[str] = [LAYER_D_HEADER, ""]
    lines.append(
        "_Generated by `gist-lowerbound` + `bench/bounds/lowerbound/report.py`. "
        "Every row is a measured byte count, not a claim. Fail-closed: the harness "
        "exits non-zero if any candidate byte is read more than the single-pass "
        "floor, or if the independent single-pass reference disagrees with gist's "
        "real verify on any document._"
    )
    lines.append("")
    lines.append("**The floor (two parts).**")
    lines.append("")
    lines.append(
        "1. **Verify is Ω(candidate bytes), one pass.** Any algorithm that correctly "
        "decides whether a pattern occurs in a candidate document must, in the worst "
        "(adversarial) case, examine every byte of it — an unread byte could be the "
        "match, or could break one (the adversary sets it after the algorithm "
        "commits). This is the classical exact-match floor of Knuth-Morris-Pratt "
        "(1977, *SIAM J. Comput.*) and Boyer-Moore (1977, *CACM*): linear-time in "
        "the worst case, Ω(n) reads to certify absence (Boyer-Moore is sublinear on "
        "*average* — Ω(n/m) reads — but the verify-stage guarantee is Ω(candidate "
        "bytes)). gist's fused byte-class DFA "
        "(`src/kernel/regex/linear/dfa/dfa.zig`) reads each "
        "candidate byte **exactly once** — a single forward pass, detecting `\\n` "
        "inline, with none of the memchr-then-rescan double byte-traffic a per-line "
        "matcher pays. The SIMD literal path "
        "(`src/kernel/scan/simd.zig`) reads **≤ N** "
        "(vector first/last-byte skips, early exit on the first hit)."
    )
    lines.append("")
    lines.append(
        "2. **The trigram filter makes total work sublinear.** gist reads far fewer "
        "than the corpus's bytes because the trigram index prunes the candidate set "
        '*before* verify runs — the technique of Russ Cox, *"Regular Expression '
        'Matching with a Trigram Index, or How Google Code Search Worked"* (2012), '
        "gist's direct ancestor. `cand%` below is the fraction of corpus bytes "
        "admitted; `100% - cand%` is pruned away untouched."
    )
    lines.append("")
    lines.append(
        "**Conclusion.** gist's two-stage design — trigram prune, then a single "
        "fused verify pass — matches the information-theoretic floor: it reads the "
        "minimum candidate set the filter can prove necessary, and verifies each "
        "candidate byte with one pass (DFA) or fewer (SIMD-skip literals)."
    )
    lines.append("")

    corpus_bytes = rows[0].corpus_bytes if rows else 0
    corpus_docs = rows[0].corpus_docs if rows else 0
    lines.append(f"- corpus: {corpus_docs} files · {_mib(corpus_bytes)} · single-thread verify")
    lines.append(
        "- method: `candidate bytes` = Σ lengths of the docs the trigram filter "
        "admits (the full-scan verify floor); `passes` = bytes an independent "
        "single-pass reference touches ÷ candidate bytes — **exactly 1.0000 for the "
        "fused DFA** (each candidate byte once, no double traffic), **≤ 1 for the "
        "SIMD literal path** (skips + early exit). The reference's match verdict is "
        "asserted equal to gist's real verify on every document."
    )
    lines.append("")
    lines.append(
        "| class | engine | corpus bytes | candidate bytes | cand% (pruned) "
        "| passes / candidate byte | hits | verdict |"
    )
    lines.append("|---|---|--:|--:|--:|--:|--:|:--|")
    all_floor = True
    for r in rows:
        all_floor = all_floor and r.at_floor
        pruned = 100.0 - r.cand_byte_frac * 100.0
        verdict = "✅ at floor" if r.at_floor else "❌ VIOLATION"
        lines.append(
            f"| `{r.cls}` | {r.engine} | {_mib(r.corpus_bytes)} | {_mib(r.cand_bytes)} "
            f"| {r.cand_byte_frac * 100.0:.2f}% ({pruned:.2f}% pruned) "
            f"| {r.passes:.4f} | {r.hits} | {verdict} |"
        )
    lines.append("")

    fused = [r for r in rows if r.passes >= 0.9999 and "dfa" in r.engine]
    classrun = [r for r in fused if "class-run" in r.engine]
    simd = [r for r in rows if "simd" in r.engine]
    if all_floor:
        # A dense class (`\w{3,8}`) is served in production by the SIMD class-run
        # kernel; its floor is certified against an independent one-pass DFA
        # reference (docMatch verdict proven equal on every candidate document).
        cr_clause = (
            f" — {len(classrun)} of them a dense class the production SIMD class-run "
            "kernel serves, proven equal on every document to an independent one-pass "
            "DFA reference"
            if classrun
            else ""
        )
        lines.append(
            f"> **At the floor on every class.** {len(fused)} classes touch every "
            "candidate byte exactly once (passes ≡ 1.0000 — a single fused pass, no "
            f"re-scan){cr_clause}; the {len(simd)} SIMD literal classes stay strictly "
            "below it (early exit + vector skips). No implementation can verify a "
            "candidate set in fewer than Ω(candidate bytes) reads, and gist reads that "
            "minimum — the trigram filter having already pruned the rest of the corpus "
            "untouched."
        )
    else:
        offenders = ", ".join(f"`{r.cls}`" for r in rows if not r.at_floor)
        lines.append(
            f"> ⚠ **Floor violation** in: {offenders}. gist read more than the "
            "single-pass floor (or the reference disagreed with production) — a real "
            "finding, not a rounding artifact. Investigate before trusting Layer D."
        )
    lines.append("")
    return "\n".join(lines)


def splice(cert: Path, section: str) -> None:
    """Replace the Layer D section (header → next `## Layer`/EOF); append if absent."""
    if not cert.exists():
        msg = (
            f"{cert} not found — run `zig build certify` (or `gist-bench certify`) "
            "first to create CERTIFICATE.md, then re-run this splicer."
        )
        raise SystemExit(msg)
    text = cert.read_text()
    start = text.find(LAYER_D_HEADER)
    if start == -1:
        head = text.rstrip() + "\n\n"
        cert.write_text(head + section)
        return
    # Find the next top-level "## Layer" heading after ours (so we replace only
    # Layer D, leaving any later section intact); else replace to EOF.
    after = text.find("\n## Layer", start + len(LAYER_D_HEADER))
    tail = text[after + 1 :] if after != -1 else ""
    head = text[:start].rstrip() + "\n\n"
    cert.write_text(head + section + ("\n" + tail if tail else ""))


def main() -> int:
    """CLI entry point."""
    # GIST_DIR first, then the package's own `.gist` — the same order `outDir()`
    # in `home.zig` resolves, so the splicer reads the file the lane just wrote
    # even when a mint relocated the artifact home. Anchored off this file rather
    # than the CWD so it works from anywhere, like the zig steps and port/mca.sh.
    out_dir = Path(
        os.environ.get("GIST_DIR") or Path(__file__).resolve().parents[3] / ".gist"
    )
    ap = argparse.ArgumentParser(description="gist Layer D lower-bound certificate splicer")
    ap.add_argument(
        "--csv",
        type=Path,
        default=out_dir / "lowerbound.csv",
        help="lowerbound.csv from gist-lowerbound",
    )
    ap.add_argument(
        "--certificate",
        type=Path,
        default=out_dir / "CERTIFICATE.md",
        help="CERTIFICATE.md to splice into",
    )
    args = ap.parse_args()

    rows = load_rows(args.csv)
    if not rows:
        print("lowerbound_report: empty CSV — did gist-lowerbound run?")
        return 1
    section = render(rows)
    splice(args.certificate, section)
    floor = sum(r.at_floor for r in rows)
    print(f"Layer D: {floor}/{len(rows)} classes at the floor")
    print(f"wrote {args.certificate} (Layer D section)")
    return 0 if floor == len(rows) else 1


if __name__ == "__main__":
    raise SystemExit(main())
