"""Detector proofs for zig-assay-bypass — the call counts, the prose does not."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from assay_bypass_ratchet import REPO, SINK_FILES, _scan_one, count_bypasses, scan  # noqa: E402


class CountBypassesTest(unittest.TestCase):
    def test_call_counted(self) -> None:
        self.assertEqual(
            1, count_bypasses('fn note() void {\n    std.debug.print("x\\n", .{});\n}\n')
        )

    def test_two_calls_counted_separately(self) -> None:
        src = (
            "fn note() void {\n"
            '    std.debug.print("a\\n", .{});\n'
            '    std.debug.print("b\\n", .{});\n'
            "}\n"
        )
        self.assertEqual(2, count_bypasses(src))

    def test_line_comment_mention_is_prose(self) -> None:
        self.assertEqual(
            0,
            count_bypasses("fn note() void {\n    // std.debug.print(...) bypasses assay\n}\n"),
        )

    def test_doc_comment_mention_is_prose(self) -> None:
        # outcome.zig's live shape: the bypass is named to record that it isn't used.
        src = (
            "/// Routed through `assay.diag` rather than `std.debug.print` so it obeys the\n"
            "/// sink.\npub fn close() void {}\n"
        )
        self.assertEqual(0, count_bypasses(src))

    def test_string_literal_mention_is_prose(self) -> None:
        self.assertEqual(
            0,
            count_bypasses('fn hint() void {\n    const s = "std.debug.print(";\n    _ = s;\n}\n'),
        )

    def test_inline_test_block_write_allowed(self) -> None:
        self.assertEqual(
            0, count_bypasses('test "dump" {\n    std.debug.print("{d}\\n", .{n});\n}\n')
        )

    def test_code_after_an_inline_test_block_still_counted(self) -> None:
        src = (
            'test "dump" {\n    std.debug.print("a\\n", .{});\n}\n'
            'fn f() void {\n    std.debug.print("b\\n", .{});\n}\n'
        )
        self.assertEqual(1, count_bypasses(src))

    def test_assay_qualified_call_not_matched(self) -> None:
        self.assertEqual(
            0, count_bypasses('fn note() void {\n    assay.diag(.warm, "x\\n", .{});\n}\n')
        )


class ScopeTest(unittest.TestCase):
    def test_sink_files_are_exempt_and_exist(self) -> None:
        # A stale path here would silently re-arm the circularity, so the
        # exemption is pinned to files that must be on disk.
        self.assertEqual(2, len(SINK_FILES))
        for p in SINK_FILES:
            self.assertTrue(p.is_file(), p)

    def test_live_scan_excludes_the_sink(self) -> None:
        scanned = {fc.rel_path for fc in scan()}
        for p in SINK_FILES:
            self.assertNotIn(str(p.relative_to(REPO)), scanned)

    def test_generated_header_skipped(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "x.zig"
            p.write_text(
                "// Code generated by tool. DO NOT EDIT.\n"
                'fn f() void {\n    std.debug.print("x\\n", .{});\n}\n',
                encoding="utf-8",
            )
            self.assertIsNone(_scan_one(p))

    def test_unreadable_file_fails_closed(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "x.zig"
            p.write_bytes(b"\xff\xfe\x00bad utf8 \xff")
            with self.assertRaises(SystemExit):
                _scan_one(p)


if __name__ == "__main__":
    unittest.main()
