//! Generated by tools/build_schema_tables.py from contract/analytic.toml — DO NOT EDIT.
//!
//! The analytic plane's row-schema table. `rows.zig` builds rows
//! against it and `irregex_schema_get` hands it to a host verbatim, so the
//! engine and every binding answer to one declaration.

const rows = @import("rows.zig");

/// A sha256 over the canonical table — `irregex_schema_digest`. A binding
/// compares its own generated constant to this at load.
pub const digest: [*:0]const u8 = "fe410e7f8ccb9a62c71bd28161f2e080";

pub const Tag = enum(u32) { text, i64, f64, bool, @"enum", texts, rows };

pub const Grade = enum(u32) { none, weak, moderate, strong, identical };
pub const Channel = enum(u32) { copies, twins, shapes, any };
pub const Unit = enum(u32) { file, function, match };
pub const RankKind = enum(u32) { definition, use, generated };

/// Schema ids — the wire discriminant, append-only.
pub const Id = enum(u32) {
    region = 1,
    site = 2,
    similar = 3,
    dup_pair = 4,
    cluster = 5,
    echo = 6,
    concept = 7,
    family = 8,
    distinct = 9,
    recalled = 10,
    pick = 11,
    phrase = 12,
    quotation = 13,
    attribution = 14,
    pattern_hit = 15,
    pattern_count = 16,
    reference = 17,
    dependency = 18,
    ripple = 19,
    mention = 20,
    blast = 21,
    ranked = 22,
};

/// Verb op codes.
pub const Op = enum(u32) {
    similar = 1,
    dups = 2,
    clusters = 3,
    echoes = 4,
    concepts = 5,
    fragments = 6,
    distinct = 7,
    recall = 8,
    pack = 9,
    quote = 10,
    patterns = 11,
    pattern_counts = 12,
    context = 13,
    family = 14,
    provenance = 15,
    blast = 16,
    rank = 17,
};

/// Which params family a verb's `params` pointer must be.
pub const Params = enum { compose, kinship, rank, retrieval, sweep };

/// Whether a verb streams rows or answers with exactly one.
pub const Stream = enum { one, many };

pub const Verb = struct { op: Op, params: Params, schema: Id, stream: Stream };

/// Indexed by `op - 1`.
pub const verbs = [_]Verb{
    .{ .op = .similar, .params = .kinship, .schema = .similar, .stream = .many },
    .{ .op = .dups, .params = .kinship, .schema = .dup_pair, .stream = .many },
    .{ .op = .clusters, .params = .kinship, .schema = .cluster, .stream = .many },
    .{ .op = .echoes, .params = .kinship, .schema = .echo, .stream = .many },
    .{ .op = .concepts, .params = .kinship, .schema = .concept, .stream = .many },
    .{ .op = .fragments, .params = .kinship, .schema = .family, .stream = .many },
    .{ .op = .distinct, .params = .kinship, .schema = .distinct, .stream = .many },
    .{ .op = .recall, .params = .retrieval, .schema = .recalled, .stream = .many },
    .{ .op = .pack, .params = .retrieval, .schema = .pick, .stream = .many },
    .{ .op = .quote, .params = .retrieval, .schema = .quotation, .stream = .one },
    .{ .op = .patterns, .params = .sweep, .schema = .pattern_hit, .stream = .many },
    .{ .op = .pattern_counts, .params = .sweep, .schema = .pattern_count, .stream = .many },
    .{ .op = .context, .params = .compose, .schema = .pick, .stream = .many },
    .{ .op = .family, .params = .compose, .schema = .family, .stream = .many },
    .{ .op = .provenance, .params = .compose, .schema = .attribution, .stream = .many },
    .{ .op = .blast, .params = .compose, .schema = .blast, .stream = .one },
    .{ .op = .rank, .params = .rank, .schema = .ranked, .stream = .many },
};

/// Indexed by `id - 1`; the field order IS the row's value order.
pub const schemas = [_]rows.Schema{
    .{ .struct_size = @sizeOf(rows.Schema), .id = 1, .name = "region", .nfields = 4, .reserved = 0, .fields = &fields_region },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 2, .name = "site", .nfields = 2, .reserved = 0, .fields = &fields_site },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 3, .name = "similar", .nfields = 4, .reserved = 0, .fields = &fields_similar },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 4, .name = "dup_pair", .nfields = 4, .reserved = 0, .fields = &fields_dup_pair },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 5, .name = "cluster", .nfields = 3, .reserved = 0, .fields = &fields_cluster },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 6, .name = "echo", .nfields = 6, .reserved = 0, .fields = &fields_echo },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 7, .name = "concept", .nfields = 6, .reserved = 0, .fields = &fields_concept },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 8, .name = "family", .nfields = 7, .reserved = 0, .fields = &fields_family },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 9, .name = "distinct", .nfields = 5, .reserved = 0, .fields = &fields_distinct },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 10, .name = "recalled", .nfields = 6, .reserved = 0, .fields = &fields_recalled },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 11, .name = "pick", .nfields = 5, .reserved = 0, .fields = &fields_pick },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 12, .name = "phrase", .nfields = 4, .reserved = 0, .fields = &fields_phrase },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 13, .name = "quotation", .nfields = 6, .reserved = 0, .fields = &fields_quotation },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 14, .name = "attribution", .nfields = 5, .reserved = 0, .fields = &fields_attribution },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 15, .name = "pattern_hit", .nfields = 3, .reserved = 0, .fields = &fields_pattern_hit },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 16, .name = "pattern_count", .nfields = 2, .reserved = 0, .fields = &fields_pattern_count },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 17, .name = "reference", .nfields = 4, .reserved = 0, .fields = &fields_reference },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 18, .name = "dependency", .nfields = 3, .reserved = 0, .fields = &fields_dependency },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 19, .name = "ripple", .nfields = 3, .reserved = 0, .fields = &fields_ripple },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 20, .name = "mention", .nfields = 3, .reserved = 0, .fields = &fields_mention },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 21, .name = "blast", .nfields = 10, .reserved = 0, .fields = &fields_blast },
    .{ .struct_size = @sizeOf(rows.Schema), .id = 22, .name = "ranked", .nfields = 5, .reserved = 0, .fields = &fields_ranked },
};

const fields_region = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line_start", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line_end", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "headline", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 1, .reserved = 0 },
};

const fields_site = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_similar = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "grade", .tag = @intFromEnum(Tag.@"enum"), .nested = 1, .optional = 0, .reserved = 0 },
    .{ .name = "channel", .tag = @intFromEnum(Tag.@"enum"), .nested = 2, .optional = 0, .reserved = 0 },
};

const fields_dup_pair = [_]rows.Field{
    .{ .name = "a", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "b", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "grade", .tag = @intFromEnum(Tag.@"enum"), .nested = 1, .optional = 0, .reserved = 0 },
};

const fields_cluster = [_]rows.Field{
    .{ .name = "paths", .tag = @intFromEnum(Tag.texts), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "max_distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "grade", .tag = @intFromEnum(Tag.@"enum"), .nested = 1, .optional = 0, .reserved = 0 },
};

const fields_echo = [_]rows.Field{
    .{ .name = "a", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "b", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "echo", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "byte_distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "structure_distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "grade", .tag = @intFromEnum(Tag.@"enum"), .nested = 1, .optional = 0, .reserved = 0 },
};

const fields_concept = [_]rows.Field{
    .{ .name = "members", .tag = @intFromEnum(Tag.rows), .nested = 1, .optional = 0, .reserved = 0 },
    .{ .name = "repeated_lines", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "confidence", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "structure_distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "byte_distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 1, .reserved = 0 },
    .{ .name = "echo", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 1, .reserved = 0 },
};

const fields_family = [_]rows.Field{
    .{ .name = "rank", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "unit", .tag = @intFromEnum(Tag.@"enum"), .nested = 3, .optional = 0, .reserved = 0 },
    .{ .name = "channel", .tag = @intFromEnum(Tag.@"enum"), .nested = 2, .optional = 0, .reserved = 0 },
    .{ .name = "edge", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "repeated_lines", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "score", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "members", .tag = @intFromEnum(Tag.rows), .nested = 1, .optional = 0, .reserved = 0 },
};

const fields_distinct = [_]rows.Field{
    .{ .name = "unit", .tag = @intFromEnum(Tag.@"enum"), .nested = 3, .optional = 0, .reserved = 0 },
    .{ .name = "member", .tag = @intFromEnum(Tag.rows), .nested = 1, .optional = 0, .reserved = 0 },
    .{ .name = "nearest", .tag = @intFromEnum(Tag.rows), .nested = 1, .optional = 1, .reserved = 0 },
    .{ .name = "byte_distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "structure_distance", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_recalled = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "gain", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "cost_bits", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "bits_saved", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "factors", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "literals", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_pick = [_]rows.Field{
    .{ .name = "rank", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "marginal_bits", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "coverage", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "patterns", .tag = @intFromEnum(Tag.texts), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_phrase = [_]rows.Field{
    .{ .name = "text", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "occurrences", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "bits", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "source", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 1, .reserved = 0 },
};

const fields_quotation = [_]rows.Field{
    .{ .name = "bits", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "bits_per_byte", .tag = @intFromEnum(Tag.f64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "quoted_bytes", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "query_bytes", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "escapes", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "phrases", .tag = @intFromEnum(Tag.rows), .nested = 12, .optional = 0, .reserved = 0 },
};

const fields_attribution = [_]rows.Field{
    .{ .name = "text", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "occurrences", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "source", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 1, .reserved = 0 },
    .{ .name = "verified", .tag = @intFromEnum(Tag.bool), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 1, .reserved = 0 },
};

const fields_pattern_hit = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "pattern_id", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_pattern_count = [_]rows.Field{
    .{ .name = "label", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "count", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_reference = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "enclosing", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 1, .reserved = 0 },
    .{ .name = "defines", .tag = @intFromEnum(Tag.bool), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_dependency = [_]rows.Field{
    .{ .name = "symbol", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_ripple = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "via", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "hops", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_mention = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "text", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_blast = [_]rows.Field{
    .{ .name = "symbol", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "kind", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "definitions", .tag = @intFromEnum(Tag.rows), .nested = 2, .optional = 0, .reserved = 0 },
    .{ .name = "dependents", .tag = @intFromEnum(Tag.rows), .nested = 17, .optional = 0, .reserved = 0 },
    .{ .name = "dependencies", .tag = @intFromEnum(Tag.rows), .nested = 18, .optional = 0, .reserved = 0 },
    .{ .name = "twins", .tag = @intFromEnum(Tag.rows), .nested = 3, .optional = 0, .reserved = 0 },
    .{ .name = "ripple", .tag = @intFromEnum(Tag.rows), .nested = 19, .optional = 0, .reserved = 0 },
    .{ .name = "comments", .tag = @intFromEnum(Tag.rows), .nested = 20, .optional = 0, .reserved = 0 },
    .{ .name = "notes", .tag = @intFromEnum(Tag.texts), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "omitted", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
};

const fields_ranked = [_]rows.Field{
    .{ .name = "path", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "line_number", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "kind", .tag = @intFromEnum(Tag.@"enum"), .nested = 4, .optional = 0, .reserved = 0 },
    .{ .name = "count", .tag = @intFromEnum(Tag.i64), .nested = 0, .optional = 0, .reserved = 0 },
    .{ .name = "snippet", .tag = @intFromEnum(Tag.text), .nested = 0, .optional = 1, .reserved = 0 },
};
