"""Fail-closed proofs for the zig-oom detector (`count_oom` / `_scan_one`)."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from oom_ratchet import _scan_one, count_oom  # noqa: E402


class CountOomTest(unittest.TestCase):
    def test_inline_die_outside_oom_fn_counted(self) -> None:
        src = 'fn parse(a: u8) void {\n    if (a == 0) die("oom\\n", .{});\n}\n'
        self.assertEqual(count_oom(src).total, 1)

    def test_inline_die_inside_canonical_pub_oom_exempt(self) -> None:
        src = 'pub fn oom() noreturn {\n    die("oom\\n", .{});\n}\n'
        self.assertEqual(count_oom(src).total, 0)

    def test_non_pub_fn_oom_def_counted(self) -> None:
        src = "fn oom() noreturn {\n    std.process.exit(2);\n}\n"
        self.assertEqual(count_oom(src).total, 1)

    def test_pub_fn_oom_def_not_counted(self) -> None:
        src = "pub fn oom() noreturn {\n    std.process.exit(2);\n}\n"
        self.assertEqual(count_oom(src).total, 0)

    def test_comment_and_string_matches_not_counted(self) -> None:
        src = (
            "fn helper() void {\n"
            '    // die("oom in a comment must not count\n'
            '    const msg = "call die(\\"oom\\") later";\n'
            "    _ = msg;\n"
            "}\n"
        )
        self.assertEqual(count_oom(src).total, 0)

    def test_multiline_string_lines_not_counted(self) -> None:
        src = (
            "fn doc() void {\n"
            "    const s =\n"
            '        \\\\die("oom in a multiline string\n'
            "    ;\n"
            "    _ = s;\n"
            "}\n"
        )
        self.assertEqual(count_oom(src).total, 0)

    def test_die_in_non_oom_fn_after_oom_fn_counted(self) -> None:
        # The exemption is per nearest-enclosing-fn, not per file.
        src = (
            'pub fn oom() noreturn {\n    die("oom\\n", .{});\n}\n'
            'fn other() void {\n    die("oom\\n", .{});\n}\n'
        )
        self.assertEqual(count_oom(src).total, 1)


class ScanOneTest(unittest.TestCase):
    def test_temp_file_with_inline_die_counted(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "x.zig"
            p.write_text('fn go() void {\n    die("oom\\n", .{});\n}\n', encoding="utf-8")
            fc = _scan_one(p, repo=Path(td))
            self.assertIsNotNone(fc)
            self.assertEqual(fc.count, 1)

    def test_generated_header_skipped(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "x.zig"
            p.write_text(
                "// Code generated by tool. DO NOT EDIT.\n"
                'fn go() void {\n    die("oom\\n", .{});\n}\n',
                encoding="utf-8",
            )
            self.assertIsNone(_scan_one(p, repo=Path(td)))

    def test_unreadable_file_fails_closed(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "x.zig"
            p.write_bytes(b"\xff\xfe\x00bad utf8 \xff")
            with self.assertRaises(SystemExit):
                _scan_one(p, repo=Path(td))


if __name__ == "__main__":
    unittest.main()
